#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start