#!/usr/bin/env bash
# This script configures Nginx with a custom HTTP response header on a new Ubuntu machine


sudo apt-get update
sudo apt-get install -y nginx

custom_header_config="add_header X-Served-By \$hostname;"

sudo sed -i "/^server {/a \ \ \ \ $custom_header_config" /etc/nginx/sites-available/default
sudo service nginx restart
