#!/usr/bin/env bash
# web static debugging

sudo apt-get update
sudo apt-get install -y nginx
if ! systemctl is-active --quiet nginx; then sudo systemctl start nginx; echo "Nginx started."; fi

if ! sudo netstat -tulpn | grep -q ":80"; then
    sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
    echo "server { listen 80 default_server; listen [::]:80 default_server; server_name _; location / { root /var/www/html; index index.html index.htm; }}" | sudo tee /etc/nginx/sites-available/default > /dev/null
    sudo systemctl reload nginx
    echo "Nginx configured to listen on port 80."
else
    echo "Nginx is already listening on port 80."
fi
