#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely with a sleep 2 in between each iteration

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincble!!!"' SIGTERM
done
