#!/usr/bin/env bash
# Script is displaying numbers from 1 to 20

k=1
while ((k < 21))
do
	echo "$k"
	case "$k" in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
		esac
	((k++))
done
