#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on all active IPs on port 8080.
# Update Nginx configuration to use the nginx user
sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf

# Update Nginx configuration to listen on all active IPs and port 8080
sed -i 's/^listen 80;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# change permission on nginx.cond
chmod 644 /etc/nginx/nginx.conf

#kill apache2 service
pkill apache2

# Restart Nginx to apply changes
sudo -u nginx service nginx restart
