#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on all active IPs on port 8080.
# Update Nginx configuration to use the nginx user

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# change permission on nginx.cond
chmod 644 /etc/nginx/nginx.conf

#kill apache2 service
pkill apache2

sudo -u nginx service nginx restart